; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Force PlatformIO to use your specific USB device
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001

; Set your serial monitor speed to match your code
monitor_speed = 115200

; This filter helps clean up output and decodes crashes if they happen
monitor_filters = esp32_exception_decoder