#ifndef COMMON_H
#define COMMON_H

//#define DEBUG 1 

#define ENABLE_SERIAL 1

#define TOC_1_ENABLE_PORT 4
#define TOC_1_CLOSE_PORT 32
#define TOC_1_THROWN_PORT 33
#define TOC_2_ENABLE_PORT 13
#define TOC_2_CLOSE_PORT 16
#define TOC_2_THROWN_PORT 17
#define TOC_3_ENABLE_PORT 14
#define TOC_3_CLOSE_PORT 18
#define TOC_3_THROWN_PORT 19
#define TOC_4_ENABLE_PORT 23
#define TOC_4_CLOSE_PORT 21
#define TOC_4_THROWN_PORT 22

#endif